default: &default
  deploy_to: "/home/deploy/consul"
  ssh_port: "22"
  user: "deploy"
  app_name: "consul"

staging:
  <<: *default
  server: "staging.consul.es"

preproduction:
  <<: *default
  server: xxx.xxx.xxx.xxx

production:
  deploy_to: "/home/deploy/consul"
  ssh_port: "22"
  server1: "68.221.171.48"
  user: "deploy"
