default: &default
  deploy_to: "/home/azureuser/consul"
  ssh_port: "22"
  user: "azureuser"
  app_name: "consul"

staging:
  <<: *default
  server: "staging.consul.es"

preproduction:
  <<: *default
  server: xxx.xxx.xxx.xxx

production:
  deploy_to: "/home/azureuser/consul"
  ssh_port: "22"
  server1: "68.221.168.23"
  user: "azureuser"
